# -*- coding: utf-8 -*-
"""test2_KOVAIco.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dre2A3eGey4HLpPdyd_6OE1ptMy98qVA
"""

#importing necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#reading dataset
data=pd.read_csv('/content/Video Games Sales - Video Games Sales.csv.csv')

#getting an info on the data
data.info()

#shape of data
data.shape

data.head()

data.tail()

#checking for null values in data
data.isnull().sum()

#imputing null values
data['Year']=data['Year'].fillna('unknown')

#drooping the null values
data=data.dropna(axis=0)

data

plt.figure(figsize=(10,10))
sns.countplot(data['Genre'])

#getting the firt 100 ranked records and last 100
high_rank=data[(data['Rank'] <=100)]
low_rank=data[(data['Rank'] >1807)]

high_rank

low_rank

#region wise average sales
print("global:",high_rank['Global'].mean())
print("north america: ",high_rank['North America'].mean())
print("europe:",high_rank['Europe'].mean())
print("Japan:",high_rank['Japan'].mean())

#understanding which genre has been most ranked
plt.figure(figsize=(10,10))
sns.countplot(high_rank['Genre'])

#genre of low ranked games
plt.figure(figsize=(10,10))
sns.countplot(low_rank['Genre'])

#count of games under publishers with rank less than 100
plt.figure(figsize=(18,10))
sns.countplot(high_rank['Publisher'])

x=